
//export const USER_DASHBOARD = 'USER_DASHBOARD'; 
//export const USER_DASHBOARD_FILTERED = 'USER_DASHBOARD_FILTERED';
export const USER_DASHBOARD_OFFLINE = 'USER_DASHBOARD_OFFLINE';
export const USER_TASKS_OFFLINE = 'USER_TASKS_OFFLINE';
export const USER_NOTES_OFFLINE = 'USER_NOTES_OFFLINE';
export const USER_OFFLINE_SHIFT_DETAIL = 'USER_OFFLINE_SHIFT_DETAIL';
export const SERVER_ERROR = 'SERVER_ERROR'; 
export const USER_DASHBOARD_NOTIFICATIONS = 'USER_DASHBOARD_NOTIFICATIONS';

               